BurgerCambodia/burgershop/burgerapp/urls.py
from django.urls import include, re_path
from django.conf import settings 

from burgerapp import views as burgerapp_view
from . import views
from burgerapp.views import *
from django.urls import path
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .models import UserProfile
from django.contrib.auth.models import User
from django.views.generic import RedirectView
from django.urls import re_path
from burgerapp import views

app_name = 'burgerapp'
urlpatterns = [
    # url('^home/$', staff_view.home_page, name='home'),
    re_path('^homepage/$', burgerapp_view.homepage, name='homepage'),
    re_path('^menupage/$', burgerapp_view.menu, name='menupage'),
    re_path('^promotionpage/$', burgerapp_view.promotion, name='promotionpage'),
    re_path('^aboutuspage/$', burgerapp_view.aboutus, name='aboutuspage'),
    re_path('^contactus/$', burgerapp_view.contactus, name='contactus'),
    re_path('^Newspage/$', burgerapp_view.news, name='news'),
    # re_path('^Signin/$', burgerapp_view.signin, name='signin'),
    re_path('signup/', views.signup, name='signup'),
]

BurgerCambodia/burgershop/burgershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path('burgerapp/', include('burgerapp.urls')),
]

BurgerCambodia/burgershop/burgerapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    sex = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female')])
    dob = models.DateField()
    profile_image = models.ImageField(upload_to='profile_images/')

def signup(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        sex = request.POST.get('sex')
        dob = request.POST.get('dob')
        email = request.POST.get('email')
        password = request.POST.get('password')
        profile_image = request.FILES.get('profile_image')

        # Create a new User object
        user = User.objects.create_user(
            username=username,
            email=email,
            password=password
        )

        # Create a new UserProfile object
        user_profile = UserProfile.objects.create(
            user=user,
            first_name=first_name,
            last_name=last_name,
            sex=sex,
            dob=dob,
            profile_image=profile_image
        )

        # Login the user
        login(request, user)

        # Redirect to a success page or the user's profile page
        return redirect('homepage')

    template = 'signup.html'
    return render(request, template)

BurgerCambodia/burgershop/burgerapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib.auth import login

def homepage(request):
    template = 'home.html'
    return render(request, template)

def menu(request):
    template = 'menu.html'
    return render(request, template)

def promotion(request):
    template = 'promotion.html'
    return render(request, template)

def aboutus(request):
    template = 'about.html'
    return render(request, template)

def contactus(request):
    template = 'contactus.html'
    return render(request, template)

def news(request):
    template = 'news.html'
    return render(request, template)

def signup(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        sex = request.POST.get('sex')
        dob = request.POST.get('dob')
        email = request.POST.get('email')
        password = request.POST.get('password')
        profile_image = request.FILES.get('profile_image')

        # Create a new User object
        user = User.objects.create_user(
            username=username,
            email=email,
            password=password
        )

        # Create a new UserProfile object
        user_profile = UserProfile.objects.create(
            user=user,
            first_name=first_name,
            last_name=last_name,
            sex=sex,
            dob=dob,
            profile_image=profile_image
        )

        # Login the user
        login(request, user)

        # Redirect to a success page or the user's profile page
        return redirect('homepage')

    template = 'signup.html'
    return render(request, template)

BurgerCambodia/burgershop/burgershop/templates/signin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.20/dist/sweetalert2.all.min.js"></script>
</head>
<style>
    form {
  padding: 5rem 35%;
  background:#fff;
  /* opacity: 0.8; */
}

.form-control{
  width: 100%;
  box-shadow: 0 .5rem 1.5rem rgba(0, 0, 0, .1);
  padding: 1rem 1rem;
  position: relative;
  background:#eee;
}
 .form-control input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
  border-radius: 5px;
 
}
.form-control .fa-circle-xmark {
    float: right;
}
.form-control h3{
  text-align: center;
  font-size: 2rem;
}
.form-control button { 
  background-color:#0d6efd;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  border-radius: 5px;
}

button:hover {
  opacity: 0.8;
}
.form-control i{
  font-size: 1rem;
}
.form-control .socail-platform{
  display: flex;
  flex-wrap: wrap;
  gap: 1.5rem;
  padding: 0.5rem 4rem;
  text-align: center;
}
.icon1{
  flex: 1 1 4rem;
  height: 2rem;
  line-height: 2rem;
  color: #fff;
  border-radius: 5px;
  background-color: #0d6efd;
}
.icon2{
  flex: 1 1 4rem;
  height: 2rem;
  line-height: 2rem;
  color: #fff;
  border-radius: 5px;
  background: radial-gradient(circle farthest-corner at 35% 90%, #fec564, transparent 50%), radial-gradient(circle farthest-corner at 0 140%, #fec564, transparent 50%), radial-gradient(ellipse farthest-corner at 0 -25%, #5258cf, transparent 50%), radial-gradient(ellipse farthest-corner at 20% -50%, #5258cf, transparent 50%), radial-gradient(ellipse farthest-corner at 100% 0, #893dc2, transparent 50%), radial-gradient(ellipse farthest-corner at 60% -20%, #893dc2, transparent 50%), radial-gradient(ellipse farthest-corner at 100% 100%, #d9317a, transparent), linear-gradient(#6559ca, #bc318f 30%, #e33f5f 50%, #f77638 70%, #fec66d 100%);
}
.form-control .fa-instagram{
  padding: 0.3rem;
}
.form-control .fa-facebook{
  padding: 0.3rem;
}
.form-control p{
  font-size: 0.9rem;
  text-align: center;
  font-family: Georgia, 'Times New Roman', Times, serif;
}
.form-control a{
  text-decoration: none;
}
@media (max-width:991px) {

  form{
    padding: 1rem 4rem;
  }
}

@media (max-width:768px) {

  form{
    padding: 1rem 2rem;
  }
}
@media (max-width:450px) {

  html {
      font-size: 80%;
      margin: 0;
  }
  form{
    padding: 1rem 1rem;
  }
  .socail-platform{
    height: fit-content;
  }
}
</style>
<body>
  <form id="loginForm" action="{% url 'burgerapp:signin' %}" method="POST">
    {% csrf_token %}
    <div class="form-control">
      <a href="{% url 'burgerapp:homepage' %}"><i class="fa-regular fa-circle-xmark"></i></a>
      <h3>Login form</h3>
      <div class="input-box">
        <label for="email">Email</label>
        <input type="text" id="email" name="email" placeholder="Your Email">
      </div>
      <div class="input-box">
        <label for="password">Password</label>
        <input type="password" id="password" name="password" placeholder="Password">
      </div>
      <button type="submit" class="submit">Login</button>
      <p>Login with other account</p>
      <div class="socail-platform">
        <div class="icon1">
          <i class="fa-brands fa-facebook"></i>Facebook
        </div>
        <div class="icon2">
          <i class="fa-brands fa-instagram"></i>Instagram
        </div>
      </div>
      <p>Don't have an account? <a href="{% url 'burgerapp:signup' %}">Sign Up now</a></p>
    </div>
    {% if error %}
    <p>{{ error }}</p>
  {% endif %}
  </form>

  <script>
    const loginForm = document.getElementById('loginForm');

    loginForm.addEventListener('submit', function(event) {
      event.preventDefault();

      const email = document.getElementById('email').value;
      const password = document.getElementById('password').value;

      // Create a FormData object and append the email and password
      const formData = new FormData();
      formData.append('email', email);
      formData.append('password', password);

      // Send a POST request to the sign-in URL
      fetch(loginForm.action, {
          method: 'POST',
          body: formData
        })
        .then(response => {
          if (response.ok) {
            // Redirect to the homepage or perform other actions
            window.location.href = "{% url 'burgerapp:homepage' %}";
          } else {
            // Handle the error case
            console.error('Login failed');
            Swal.fire(
              'Error',
              'Login failed',
              'error'
            );
          }
        })
        .catch(error => {
          console.error(error);
          Swal.fire(
            'Error',
            'An error occurred',
            'error'
          );
        });
    });
  </script>
</body>
</html>

BurgerCambodia/burgershop/burgershop/templates/signup.html
{% load static %}
<!-- SweetAlert CSS -->
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.4/dist/sweetalert2.min.css">

<!-- SweetAlert JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.4/dist/sweetalert2.min.js"></script>
<style>
    * {
        padding: 0;
        margin: 0;
    }

    body {
        font-family: var(--primary-font);
    }

    :root {
        --primary-font: "Quicksand", sans-serif;
        --secondary-font: "Poppins", sans-serif;
        --first-color: #fffdd0;
        --second-color: #a0522d;
    }

    h1.create-acc {
        font-family: var(--primary-font);
        font-size: 23px;
        text-align: center;
    }

    form {
        border-radius: 5px;
        width: 30%;
        box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 1px 3px 1px;
        padding: 30px;
    }

    .personal-info {
        padding: 10px 0;
        margin-bottom: 20px;
    }

    .personal-info h3 {
        margin: 30px 0;
    }

    .custom-select {
        font-family: var(--secondary-font);
        display: block;
        width: 95%;
        padding: 15px 10px;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 2px solid var(--second-color);
        border-radius: 20px;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    /* Custom styling for the date of birth input */
    [type="date"].form-control {
        display: block;
        padding: 15px 10px;
        width: 95%;
        border: 2px solid var(--second-color);
        border-radius: 20px;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .personal-info input {
        margin: 20px 0;
        border-radius: 20px;
        outline: 0;
        font-size: 17px;
        padding: 15px 10px;
        font-family: var(--secondary-font);
        border: 2px solid var(--second-color);
    }

    .container {
        margin-top: 20vh;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .personal-info input[type="text"] {
        display: block;
        width: 95%;
    }

    .personal-info input[type="password"] {
        display: block;
        width: 95%;
    }

    .personal-info input[type="email"] {
        display: block;
        width: 95%;
    }

    .term-of-use .ctn {
        padding: 10px 0;
        display: flex;
        flex-wrap: wrap;
        align-items: center;
    }

    button.btn-primary {
        margin: 15px 10px;
        float: right;
        background-color: #fffdd0;
        border-radius: 50px;
        padding: 10px;
        font-family: var(--primary-font);
        transition: 0.5s ease;
        border: 1px solid black;
    }

    button.btn-primary:hover {
        background-color: black;
        color: white;
    }

    .ctn {

        width: fit-content;
        margin-right: 10px;
    }

    .ctn input {
        zoom: 1.5;
    }




    @media (max-width: 767px) {
        form {
            padding: 15px;
            width: 80%;
        }

        .personal-info,
        .term-of-use {
            margin-bottom: 15px;
        }

        .personal-info,
        .term-of-use .ctn {
            width: 100%;
        }

        .ctn {
            margin-right: 0;
        }
    }

    .go-back-btn {
        display: flex;
        margin: 10px 0 0 50px;
        border: 1px solid black;
        width:75px;
        padding:7px;
        border-radius: 20px;
        background-color: #a0522d;
        color:white;
        text-decoration: none;
        transition: 0.5s ease;
    }
    .go-back-btn:hover{
        background-color: #495057;
    }
    label.pfp{
        font-size: 20px;
        font-family: var(--primary-font);
        font-weight: bold;
        margin-right: 55px;
    }
</style>
<a href="{% url 'burgerapp:menupage' %}" class="go-back-btn">Go Back</a>

<h1 class="create-acc">Create an account</h1>
<div class="container">
    <form method="post" action="{% url 'burgerapp:signup' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="personal-info">
                    <h6>* indicates required field</h6>
                    <h3>Personal Information</h3>
                    <input type="text" class="form-control" placeholder="* First name" name="first_name">
                    <input type="text" class="form-control" placeholder="* Last name" name="last_name">
                    <input type="text" class="form-control" placeholder="* Username" name="username">
                  
                    <div class="alert alert-danger"></div>
            
                    <select class="form-control custom-select" name="sex">
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                    <input type="date" class="form-control" placeholder="* Date of Birth" name="dob">
                    <label for="profile_image" class="pfp">Profile Picture</label>
                    <input type="file" class="form-control-file pfp" name="profile_image">
                </div>
            </div>
            <div class="col-md-6">
                <div class="personal-info">
                    <h3>Account Security</h3>
                    <input type="email" class="form-control" placeholder="* Email address" name="email">
               
                    <div class="alert alert-danger"></div>
            
                    <input type="password" class="form-control" placeholder="* Password" name="password">
                    <h6 class="pass-warn">Create a password 8 to 25 characters long that includes at least 1 uppercase
                        and 1 lowercase letter, 1 number and 1 special character like an exclamation point or asterisk.
                    </h6>
                </div>
            </div>
        </div>
        <div class="term-of-use">
            <h3>TERMS OF USE</h3>
            <div class="ctn">
                <div class="form-check">
                    <input class="form-check-input bigger-checkbox" type="checkbox" id="myCheckbox">
                </div>
            </div>
            <div class="ctn ctn-text">
                <p>I agree to the Starbucks® Rewards Terms opens in new window and the Starbucks Card Terms opens in new
                    window and have read the Starbucks Privacy Statement opens in new window.</p>
            </div>
        </div>
        <button class="btn btn-primary" type="submit" id="submitButton" disabled>Create an account</button>
    </form>
    
</div>

<script>
    const form = document.querySelector('form');
    const submitButton = document.getElementById('submitButton');

    form.addEventListener('submit', function (event) {
        event.preventDefault();
        const formData = new FormData(form);
        fetch(form.action, {
            method: 'POST',
            body: formData
        })
        .then(response => {
            if (response.ok) {
                // Redirect to a success page or perform other actions
                Swal.fire(
                    'Success',
                    'Signup successful',
                    'success'
                );
            } else {
                // Handle the error case
                console.error('Signup failed');
                Swal.fire(
                    'Error',
                    'Signup fail',
                    'error'
                ).then(function(){
                    window.location.href = "{% url 'burgerapp:homepage' %}";
                })
              
            }
        })
        .catch(error => {
            console.error(error);
            Swal.fire(
                'Error',
                'An error occurred',
                'error'
            );
        });
    });

    // Enable or disable the submit button based on checkbox state
    const checkbox = document.getElementById('myCheckbox');
    checkbox.addEventListener('change', function () {
        submitButton.disabled = !checkbox.checked;
    });
</script>